-- MySQL Script generated by MySQL Workbench
-- Sun May 22 23:27:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Waterreminder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Waterreminder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Waterreminder` DEFAULT CHARACTER SET utf8 ;
USE `Waterreminder` ;

-- -----------------------------------------------------
-- Table `Waterreminder`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`CSexo` (
  `idsexo` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`idsexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`Privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`CPrivilegio` (
  `idPrivilegio` INT NOT NULL AUTO_INCREMENT,
  `privilegio` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`CRol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `peso` INT(10) NULL,
  `altura` VARCHAR(10) NULL,
  `edad` INT(10) NULL,
  `meta_agua` VARCHAR(45) NULL,
  `hora_desp` VARCHAR(45) NULL,
  `hora_dormir` VARCHAR(45) NULL,
  `Sexo_idsexo` INT NOT NULL,
  `Privilegio_idPrivilegio` INT NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idPersona`, `Sexo_idsexo`, `Privilegio_idPrivilegio`, `Rol_idRol`),
  INDEX `fk_Persona_Sexo1_idx` (`Sexo_idsexo` ASC) VISIBLE,
  INDEX `fk_Persona_Privilegio1_idx` (`Privilegio_idPrivilegio` ASC) VISIBLE,
  INDEX `fk_Persona_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Sexo1`
    FOREIGN KEY (`Sexo_idsexo`)
    REFERENCES `Waterreminder`.`Sexo` (`idsexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Privilegio1`
    FOREIGN KEY (`Privilegio_idPrivilegio`)
    REFERENCES `Waterreminder`.`Privilegio` (`idPrivilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `Waterreminder`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`Consumo_Agua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`Consumo_Agua` (
  `idConsumo_Agua`  INT NOT NULL AUTO_INCREMENT,
  `Consumo_Total` INT(10) NULL,
  `Fecha` DATE NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idConsumo_Agua`, `Persona_idPersona`),
  INDEX `fk_Consumo_Agua_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Consumo_Agua_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Waterreminder`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`CTipo_bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`CTipo_bebida` (
  `idCTipo_bebida` INT NOT NULL,
  `tipo_bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`idCTipo_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`Datos_bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`Datos_bebida` (
  `idRegistro_bebida` INT NOT NULL,
  `agua_bebida` INT(10) NULL,
  `cal_bebida` INT(10) NULL,
  `azucar_bebida` INT(10) NULL,
  `ml` INT(10) NULL,
  `CTipo_bebida_idCTipo_bebida` INT NOT NULL,
  PRIMARY KEY (`idRegistro_bebida`, `CTipo_bebida_idCTipo_bebida`),
  INDEX `fk_Registro_bebida_CTipo_bebida1_idx` (`CTipo_bebida_idCTipo_bebida` ASC) VISIBLE,
  CONSTRAINT `fk_Registro_bebida_CTipo_bebida1`
    FOREIGN KEY (`CTipo_bebida_idCTipo_bebida`)
    REFERENCES `Waterreminder`.`CTipo_bebida` (`idCTipo_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Waterreminder`.`Alarmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Waterreminder`.`Alarmas` (
  `idAlarmas` INT NOT NULL AUTO_INCREMENT,
  `Alarma` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idAlarmas`, `Persona_idPersona`),
  INDEX `fk_Alarmas_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Alarmas_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Waterreminder`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
